// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9NffVXpH5-y8J0teC5ULB86Ou04boaU',
    appId: '1:321819220856:web:4e421b1f0f2101da88068d',
    messagingSenderId: '321819220856',
    projectId: 'alu-internship-platform-f3e2c',
    authDomain: 'alu-internship-platform-f3e2c.firebaseapp.com',
    storageBucket: 'alu-internship-platform-f3e2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXneqvIyLuW-2jhftbnZOCn8rLF-2fmU',
    appId: '1:321819220856:android:91cd234a46b3068288068d',
    messagingSenderId: '321819220856',
    projectId: 'alu-internship-platform-f3e2c',
    storageBucket: 'alu-internship-platform-f3e2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7A6vLoyQuC5CT6F9TfiqvrRP7cG5Uqd4',
    appId: '1:321819220856:ios:8a33675d7ee0851f88068d',
    messagingSenderId: '321819220856',
    projectId: 'alu-internship-platform-f3e2c',
    storageBucket: 'alu-internship-platform-f3e2c.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7A6vLoyQuC5CT6F9TfiqvrRP7cG5Uqd4',
    appId: '1:321819220856:ios:8a33675d7ee0851f88068d',
    messagingSenderId: '321819220856',
    projectId: 'alu-internship-platform-f3e2c',
    storageBucket: 'alu-internship-platform-f3e2c.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV9NffVXpH5-y8J0teC5ULB86Ou04boaU',
    appId: '1:321819220856:web:6b100efc4c51eba288068d',
    messagingSenderId: '321819220856',
    projectId: 'alu-internship-platform-f3e2c',
    authDomain: 'alu-internship-platform-f3e2c.firebaseapp.com',
    storageBucket: 'alu-internship-platform-f3e2c.firebasestorage.app',
  );
}
